<?php
use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Blog\Post;

class PostTableSeeder extends Seeder{
	
	public function run(){
		Post::create(
			[
				'title' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium, amet.',
				'content' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid laudantium mollitia harum minus modi libero rem debitis ea commodi neque facere veritatis, voluptate distinctio reiciendis natus suscipit itaque culpa, veniam temporibus officiis omnis nostrum fugiat! Quibusdam corporis, saepe nisi, facere, provident facilis, sed aliquam adipisci commodi ipsam atque molestias nemo? Doloremque at iure illo fuga. Dolores nostrum molestias veritatis pariatur reiciendis reprehenderit aspernatur ut sed quidem sit, quia excepturi repellat et vero non voluptate sunt aliquid dignissimos accusantium culpa nihil recusandae! Consequuntur repellat perferendis nemo quibusdam soluta ipsum accusantium maiores, nesciunt a hic sunt minima vel vero. Consequatur nam unde consequuntur veritatis excepturi nostrum eaque magnam reprehenderit totam sapiente libero ullam natus velit maiores alias cum accusantium asperiores, ipsam sequi. Temporibus reprehenderit porro, quam nesciunt, est autem odio inventore dolorem iusto fuga expedita. Rerum quibusdam incidunt, consequatur voluptatem ut culpa praesentium fuga sed dolorum saepe omnis maxime facilis, quisquam illo, soluta consectetur ipsum non. Omnis provident enim, voluptatem harum. Molestias doloremque adipisci aut non, est, quaerat fugit eveniet ut vitae perferendis aperiam iusto unde esse aliquam ea excepturi enim nesciunt, voluptatibus odio! Distinctio cumque itaque assumenda enim odio eaque non. Perferendis alias, impedit reprehenderit placeat! Modi deserunt nihil eum delectus earum odio illo repudiandae quis incidunt, consectetur aspernatur facere tempore perspiciatis dolorem veritatis ipsum explicabo, nisi qui minus atque. Atque repudiandae aliquid fugit explicabo officia temporibus, facilis aspernatur soluta excepturi, distinctio deleniti cumque doloremque. Voluptatum reprehenderit veritatis, doloribus illo impedit, minus esse voluptate nam, error veniam pariatur voluptates, iure quam.',
				'tags'=> 'Lorem,Ipsun,Chef',
				'photo' => 'http://i.imgur.com/Cm5Qow8.jpg'
			]
		);
		Post::create(
			[
				'title' => 'Lorem ipsum dolor sit amet.',
				'content' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At saepe perferendis, quae maiores officiis, architecto, a fugiat dolorum quod enim quibusdam velit debitis recusandae magni corrupti distinctio quidem dolores ut. Similique voluptas vel odit quis maiores a officiis non ea minima, ipsum voluptatibus optio eaque, veritatis. Magni minima reprehenderit nam facilis voluptates quaerat expedita et repellat ad! Perferendis officiis similique voluptate dolor possimus nulla aliquid laborum impedit obcaecati ipsam rem ipsum, cupiditate, molestias perspiciatis alias deleniti tenetur repudiandae? Eius deserunt eos provident fuga placeat eligendi itaque architecto quaerat asperiores, saepe qui assumenda inventore dicta, libero neque, error aut impedit recusandae. Officia quisquam perferendis, necessitatibus illum veniam tempore nostrum. Possimus earum mollitia odit eos est a natus excepturi, perferendis nesciunt libero modi eum odio, aliquam culpa dolore harum, eveniet fugiat tenetur praesentium placeat voluptatum laborum veniam molestiae deleniti. Vel dolor deserunt deleniti veniam fugiat esse neque quia inventore necessitatibus voluptatibus quidem suscipit vero, temporibus aliquam. Sunt officia obcaecati, nemo voluptas vel molestias ipsam eos a dolore dolor culpa praesentium architecto aliquam debitis eveniet autem quisquam distinctio, sit molestiae cupiditate incidunt illo id rem! Sit ab quaerat, architecto blanditiis autem officiis deleniti doloribus iste amet porro veritatis pariatur voluptatum voluptatem, consectetur dolores, natus in. Eveniet explicabo maxime, facilis minus quasi laboriosam corrupti deserunt reiciendis error similique ab fugit, incidunt ratione omnis. Provident voluptatum quaerat, non. Amet, repellat, laudantium. Nam non voluptate voluptatibus rerum tenetur, magni! Unde repudiandae perspiciatis aliquam itaque assumenda. Minus sequi ex officia ratione quo harum minima adipisci rerum laboriosam.',
				'tags'=> 'Sushi,Ipsun,Chef',
				'photo' => 'http://i.imgur.com/gBTaX41.jpg'
			]
		);
		Post::create(
			[
				'title' => 'Sweet Potato Lettuce Brownie',
				'content' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At saepe perferendis, quae maiores officiis, architecto, a fugiat dolorum quod enim quibusdam velit debitis recusandae magni corrupti distinctio quidem dolores ut. Similique voluptas vel odit quis maiores a officiis non ea minima, ipsum voluptatibus optio eaque, veritatis. Magni minima reprehenderit nam facilis voluptates quaerat expedita et repellat ad! Perferendis officiis similique voluptate dolor possimus nulla aliquid laborum impedit obcaecati ipsam rem ipsum, cupiditate, molestias perspiciatis alias deleniti tenetur repudiandae? Eius deserunt eos provident fuga placeat eligendi itaque architecto quaerat asperiores, saepe qui assumenda inventore dicta, libero neque, error aut impedit recusandae. Officia quisquam perferendis, necessitatibus illum veniam tempore nostrum. Possimus earum mollitia odit eos est a natus excepturi, perferendis nesciunt libero modi eum odio, aliquam culpa dolore harum, eveniet fugiat tenetur praesentium placeat voluptatum laborum veniam molestiae deleniti. Vel dolor deserunt deleniti veniam fugiat esse neque quia inventore necessitatibus voluptatibus quidem suscipit vero, temporibus aliquam. Sunt officia obcaecati, nemo voluptas vel molestias ipsam eos a dolore dolor culpa praesentium architecto aliquam debitis eveniet autem quisquam distinctio, sit molestiae cupiditate incidunt illo id rem! Sit ab quaerat, architecto blanditiis autem officiis deleniti doloribus iste amet porro veritatis pariatur voluptatum voluptatem, consectetur dolores, natus in. Eveniet explicabo maxime, facilis minus quasi laboriosam corrupti deserunt reiciendis error similique ab fugit, incidunt ratione omnis. Provident voluptatum quaerat, non. Amet, repellat, laudantium. Nam non voluptate voluptatibus rerum tenetur, magni! Unde repudiandae perspiciatis aliquam itaque assumenda. Minus sequi ex officia ratione quo harum minima adipisci rerum laboriosam.',
				'tags'=> 'Sushi,Lorem,Chef',
				'photo' => 'http://i.imgur.com/gBTaX41.jpg'
			]
		);
		Post::create(
			[
				'title' => 'Americana The Wala Wala',
				'content' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At saepe perferendis, quae maiores officiis, architecto, a fugiat dolorum quod enim quibusdam velit debitis recusandae magni corrupti distinctio quidem dolores ut. Similique voluptas vel odit quis maiores a officiis non ea minima, ipsum voluptatibus optio eaque, veritatis. Magni minima reprehenderit nam facilis voluptates quaerat expedita et repellat ad! Perferendis officiis similique voluptate dolor possimus nulla aliquid laborum impedit obcaecati ipsam rem ipsum, cupiditate, molestias perspiciatis alias deleniti tenetur repudiandae? Eius deserunt eos provident fuga placeat eligendi itaque architecto quaerat asperiores, saepe qui assumenda inventore dicta, libero neque, error aut impedit recusandae. Officia quisquam perferendis, necessitatibus illum veniam tempore nostrum. Possimus earum mollitia odit eos est a natus excepturi, perferendis nesciunt libero modi eum odio, aliquam culpa dolore harum, eveniet fugiat tenetur praesentium placeat voluptatum laborum veniam molestiae deleniti. Vel dolor deserunt deleniti veniam fugiat esse neque quia inventore necessitatibus voluptatibus quidem suscipit vero, temporibus aliquam. Sunt officia obcaecati, nemo voluptas vel molestias ipsam eos a dolore dolor culpa praesentium architecto aliquam debitis eveniet autem quisquam distinctio, sit molestiae cupiditate incidunt illo id rem! Sit ab quaerat, architecto blanditiis autem officiis deleniti doloribus iste amet porro veritatis pariatur voluptatum voluptatem, consectetur dolores, natus in. Eveniet explicabo maxime, facilis minus quasi laboriosam corrupti deserunt reiciendis error similique ab fugit, incidunt ratione omnis. Provident voluptatum quaerat, non. Amet, repellat, laudantium. Nam non voluptate voluptatibus rerum tenetur, magni! Unde repudiandae perspiciatis aliquam itaque assumenda. Minus sequi ex officia ratione quo harum minima adipisci rerum laboriosam.',
				'tags'=> 'Sushi,Ipsun,Chef',
				'photo' => 'http://i.imgur.com/gBTaX41.jpg'
			]
		);
	}
}